AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'vendor/bundle/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/passwords_controller.rb'
    - 'app/controllers/sessions_controller.rb'
    - 'app/controllers/users_controller.rb'

Metrics/BlockNesting:
  Max: 2

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 10
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingComma:
  EnforcedStyleForMultiline: 'comma'

Style/WordArray:
  Exclude:
    - 'app/helpers/application_helper.rb'
